import {
  LayoutDashboard,
  Package,
  Boxes,
  FileText,
  Users,
  Settings,
  Folder,
  Star,
  Tag,
  Wrench,
  Kanban,
  ShoppingCart,
  History,
  ShieldCheck,
  HardHat,
  type LucideIcon,
} from "lucide-react";
import type { MenuIconName } from "@/lib/types";

export const ICON_MAP: Record<MenuIconName, LucideIcon> = {
  LayoutDashboard,
  Package,
  Boxes,
  FileText,
  Users,
  Settings,
  Folder,
  Star,
  Tag,
  Wrench,
  Kanban,
  ShoppingCart,
  History,
  ShieldCheck,
  HardHat,
};

export const ICON_OPTIONS: MenuIconName[] = [
  "LayoutDashboard",
  "Package",
  "Boxes",
  "FileText",
  "Users",
  "Folder",
  "Star",
  "Tag",
  "Wrench",
  "Kanban",
  "ShoppingCart",
  "History",
  "ShieldCheck",
  "HardHat",
  "Settings",
];

export const ROUTE_FOR_ID: Record<string, string> = {
  dashboard: "/",
  inventario: "/inventario",
  kits: "/kits",
  cotizaciones: "/cotizaciones",
  kanban: "/kanban",
  compras: "/compras",
  "audit-log": "/audit-log",
  "cotizaciones-proveedores": "/cotizaciones-proveedores",
  clientes: "/clientes",
  recordatorios: "/recordatorios",
  usuarios: "/usuarios",
  proyectos: "/proyectos",
};
