/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RecordatoriosRouteImport } from './routes/recordatorios'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitsRouteImport } from './routes/kits'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as CotizacionesProveedoresRouteImport } from './routes/cotizaciones-proveedores'
import { Route as CotizacionesRouteImport } from './routes/cotizaciones'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotizacionesIdRouteImport } from './routes/cotizaciones.$id'
import { Route as CotizacionesIdPublicaRouteImport } from './routes/cotizaciones.$id.publica'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordatoriosRoute = RecordatoriosRouteImport.update({
  id: '/recordatorios',
  path: '/recordatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitsRoute = KitsRouteImport.update({
  id: '/kits',
  path: '/kits',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesProveedoresRoute = CotizacionesProveedoresRouteImport.update({
  id: '/cotizaciones-proveedores',
  path: '/cotizaciones-proveedores',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesRoute = CotizacionesRouteImport.update({
  id: '/cotizaciones',
  path: '/cotizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionesIdRoute = CotizacionesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CotizacionesRoute,
} as any)
const CotizacionesIdPublicaRoute = CotizacionesIdPublicaRouteImport.update({
  id: '/publica',
  path: '/publica',
  getParentRoute: () => CotizacionesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/audit-log': typeof AuditLogRoute
  '/ayuda': typeof AyudaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cotizaciones': typeof CotizacionesRouteWithChildren
  '/cotizaciones-proveedores': typeof CotizacionesProveedoresRoute
  '/inventario': typeof InventarioRoute
  '/kanban': typeof KanbanRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/cotizaciones/$id': typeof CotizacionesIdRouteWithChildren
  '/cotizaciones/$id/publica': typeof CotizacionesIdPublicaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/audit-log': typeof AuditLogRoute
  '/ayuda': typeof AyudaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cotizaciones': typeof CotizacionesRouteWithChildren
  '/cotizaciones-proveedores': typeof CotizacionesProveedoresRoute
  '/inventario': typeof InventarioRoute
  '/kanban': typeof KanbanRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/cotizaciones/$id': typeof CotizacionesIdRouteWithChildren
  '/cotizaciones/$id/publica': typeof CotizacionesIdPublicaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/audit-log': typeof AuditLogRoute
  '/ayuda': typeof AyudaRoute
  '/clientes': typeof ClientesRoute
  '/compras': typeof ComprasRoute
  '/cotizaciones': typeof CotizacionesRouteWithChildren
  '/cotizaciones-proveedores': typeof CotizacionesProveedoresRoute
  '/inventario': typeof InventarioRoute
  '/kanban': typeof KanbanRoute
  '/kits': typeof KitsRoute
  '/login': typeof LoginRoute
  '/proyectos': typeof ProyectosRoute
  '/recordatorios': typeof RecordatoriosRoute
  '/usuarios': typeof UsuariosRoute
  '/cotizaciones/$id': typeof CotizacionesIdRouteWithChildren
  '/cotizaciones/$id/publica': typeof CotizacionesIdPublicaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/audit-log'
    | '/ayuda'
    | '/clientes'
    | '/compras'
    | '/cotizaciones'
    | '/cotizaciones-proveedores'
    | '/inventario'
    | '/kanban'
    | '/kits'
    | '/login'
    | '/proyectos'
    | '/recordatorios'
    | '/usuarios'
    | '/cotizaciones/$id'
    | '/cotizaciones/$id/publica'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/audit-log'
    | '/ayuda'
    | '/clientes'
    | '/compras'
    | '/cotizaciones'
    | '/cotizaciones-proveedores'
    | '/inventario'
    | '/kanban'
    | '/kits'
    | '/login'
    | '/proyectos'
    | '/recordatorios'
    | '/usuarios'
    | '/cotizaciones/$id'
    | '/cotizaciones/$id/publica'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/audit-log'
    | '/ayuda'
    | '/clientes'
    | '/compras'
    | '/cotizaciones'
    | '/cotizaciones-proveedores'
    | '/inventario'
    | '/kanban'
    | '/kits'
    | '/login'
    | '/proyectos'
    | '/recordatorios'
    | '/usuarios'
    | '/cotizaciones/$id'
    | '/cotizaciones/$id/publica'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AuditLogRoute: typeof AuditLogRoute
  AyudaRoute: typeof AyudaRoute
  ClientesRoute: typeof ClientesRoute
  ComprasRoute: typeof ComprasRoute
  CotizacionesRoute: typeof CotizacionesRouteWithChildren
  CotizacionesProveedoresRoute: typeof CotizacionesProveedoresRoute
  InventarioRoute: typeof InventarioRoute
  KanbanRoute: typeof KanbanRoute
  KitsRoute: typeof KitsRoute
  LoginRoute: typeof LoginRoute
  ProyectosRoute: typeof ProyectosRoute
  RecordatoriosRoute: typeof RecordatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordatorios': {
      id: '/recordatorios'
      path: '/recordatorios'
      fullPath: '/recordatorios'
      preLoaderRoute: typeof RecordatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kits': {
      id: '/kits'
      path: '/kits'
      fullPath: '/kits'
      preLoaderRoute: typeof KitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones-proveedores': {
      id: '/cotizaciones-proveedores'
      path: '/cotizaciones-proveedores'
      fullPath: '/cotizaciones-proveedores'
      preLoaderRoute: typeof CotizacionesProveedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones': {
      id: '/cotizaciones'
      path: '/cotizaciones'
      fullPath: '/cotizaciones'
      preLoaderRoute: typeof CotizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizaciones/$id': {
      id: '/cotizaciones/$id'
      path: '/$id'
      fullPath: '/cotizaciones/$id'
      preLoaderRoute: typeof CotizacionesIdRouteImport
      parentRoute: typeof CotizacionesRoute
    }
    '/cotizaciones/$id/publica': {
      id: '/cotizaciones/$id/publica'
      path: '/publica'
      fullPath: '/cotizaciones/$id/publica'
      preLoaderRoute: typeof CotizacionesIdPublicaRouteImport
      parentRoute: typeof CotizacionesIdRoute
    }
  }
}

interface CotizacionesIdRouteChildren {
  CotizacionesIdPublicaRoute: typeof CotizacionesIdPublicaRoute
}

const CotizacionesIdRouteChildren: CotizacionesIdRouteChildren = {
  CotizacionesIdPublicaRoute: CotizacionesIdPublicaRoute,
}

const CotizacionesIdRouteWithChildren = CotizacionesIdRoute._addFileChildren(
  CotizacionesIdRouteChildren,
)

interface CotizacionesRouteChildren {
  CotizacionesIdRoute: typeof CotizacionesIdRouteWithChildren
}

const CotizacionesRouteChildren: CotizacionesRouteChildren = {
  CotizacionesIdRoute: CotizacionesIdRouteWithChildren,
}

const CotizacionesRouteWithChildren = CotizacionesRoute._addFileChildren(
  CotizacionesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AuditLogRoute: AuditLogRoute,
  AyudaRoute: AyudaRoute,
  ClientesRoute: ClientesRoute,
  ComprasRoute: ComprasRoute,
  CotizacionesRoute: CotizacionesRouteWithChildren,
  CotizacionesProveedoresRoute: CotizacionesProveedoresRoute,
  InventarioRoute: InventarioRoute,
  KanbanRoute: KanbanRoute,
  KitsRoute: KitsRoute,
  LoginRoute: LoginRoute,
  ProyectosRoute: ProyectosRoute,
  RecordatoriosRoute: RecordatoriosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
